import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./Provider";
import FooterComponent from "@/components/homepage/footer";
import Nav from "@/components/homepage/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "African Print Cloth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <StoreProvider>
    <body className={inter.className}>
      <Nav/>
      {children}
      <FooterComponent/>
        </body>
      </StoreProvider>
    </html>

  );
}
